on: [workflow_dispatch, push]

permissions:
  contents: write

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
      nonlatest: ${{ steps.set-matrix.outputs.optionals }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          versionsAsRoot: true
          type: minors
          preset: '>= 10'

  latest:
    needs: [matrix]
    name: 'latest minors'
    runs-on: ubuntu-latest
    timeout-minutes: 120

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.matrix.outputs.latest) }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v3
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
          cache-node-modules-key: node_modules-${{ github.workflow }}-${{ github.action }}-${{ github.run_id }}
          skip-ls-check: ${{ startsWith(matrix.node-version, '0') && 'true' || 'false' }}
      - run: npm run test-failures
      - run: git pull --rebase --autostash
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'update fixture for node v${{ matrix.node-version }}'

  nonlatest:
    needs: [matrix, latest]
    name: 'non-latest minors'
    continue-on-error: true
    timeout-minutes: 120
    if: ${{ needs.matrix.outputs.nonlatest != '[]' && (!github.head_ref || !startsWith(github.head_ref, 'renovate')) }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.matrix.outputs.nonlatest) }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v3
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
          cache-node-modules-key: node_modules-${{ github.workflow }}-${{ github.action }}-${{ github.run_id }}
          skip-ls-check: true
      - run: npm run test-failures
      - run: git pull --rebase --autostash
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'update fixture for node v${{ matrix.node-version }}'

  node:
    name: node autogenerate fixtures
    needs: [latest, nonlatest]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - run: 'echo tests completed'
